apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aws-secrets
  namespace: dapr-poc
spec:
  type: secretstores.aws.secretmanager
  version: v1
  metadata:
    - name: region
      value: us-east-1
